### ISSUE TITLE
Add "HiddenStore" option

### ISSUE THREAD

**Issue by rbergo** [mastrolinux/easyftp#3]
Please add a simil-hiddenstore option like http://www.proftpd.org/docs/directives/linked/config_ref_HiddenStores.html

**Comment by mastrolinux** [comment]
Solved by: https://github.com/mastrolinux/easyftp/commit/8faea50c2efa7cd629fbb639db065dd8bfb0302f it requires the latest pyftpdlib

**Comment by rbergo** [comment]
Two questions:
1) if the user stop a file uploading pressing Ctrl+C, easyftp save the part of file uploaded as well (but it hasn't been completed). It could be better to remove the partial file.
2) To be compliant with proftpd as mentioned avove, the temp file should be `.in.` + filename + `.`

**Comment by mastrolinux** [comment]
I need to create

```
def on_incomplete_file_received(self, file):
        # remove partially uploaded files
        import os
        os.remove(file)
```

But dud not test it yet.

**Comment by rbergo** [comment]
Ok, it works !

There was `on_incomplete_received(self, file)` instead of corrected method
